# Generated by Django 4.2.8 on 2023-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naissance',
            field=models.CharField(default=454, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='niveau',
            field=models.CharField(default=879, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(default=639, max_length=10),
            preserve_default=False,
        ),
    ]
